In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [97]:
df1= pd.read_excel('core_banking_data.xlsx')
df2= pd.read_excel('customer_data.xlsx')

In [98]:
df1
df2

,CustomerID,CustomerName,Email,PhoneNumber,Address,DateOfBirth,Gender
0,e0497be9-6494-4efb-b575-fe9f55fccfe4,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male
1,112d81e0-caca-4ba3-b6ad-c31178438dac,Emily Rodriguez,allison37@example.com,8103991750,"766 Smith Pines\nMatthewland, GU 69433",2014-01-20,Male
2,ec75eb51-73ea-40a9-b865-872adf4cc66e,Valerie Erickson,deleonmary@example.net,001-518-215-9510x63655,"064 Miller Canyon\nNew Nicole, MS 14275",1959-11-04,Female
3,8b8ddb5d-2b0a-434c-a25d-b4408dffb66c,Paige Riggs,courtney78@example.net,640-816-6789,USNS Ross\nFPO AA 94265,1940-10-14,Female
4,009cbfcb-ee30-40fd-88ac-eab5e3e6ff62,Devon Wright,camachodaniel@example.com,001-402-236-4082x438,"799 William Stream Apt. 755\nGarnertown, MS 89065",1967-01-22,Male
...,...,...,...,...,...,...,...
9995,95ca5d6e-f191-49a1-9375-1fa3564cd1c9,Donna Jones,robert92@example.net,(372)675-2067,2806 Robert Knoll Suite 901\nNorth Toddborough...,2004-10-01,Female
9996,4f1e7c02-6ea9-431b-bac3-18165fcf706e,Brandon Castillo,jenniferjohnson@example.org,951-433-5371x3977,"20220 Thomas Walks Suite 452\nJacobport, MH 47614",1966-03-21,Female
9997,dd3b4013-b4ab-4876-a963-efbd308ffffc,Elizabeth Black,jacob94@example.org,(352)336-6625,"54627 Rodriguez Haven Apt. 458\nLovefurt, UT 7...",1944-08-29,Female
9998,7db9b564-678f-4acf-bb3b-c23829be84ea,Levi Flores,amber90@example.com,(855)880-5728x5549,"076 Kimberly Cape Suite 218\nAlexanderport, MT...",1913-08-21,Male
9999,5b35e7e2-25d5-4c37-908c-73b81cac087e,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female

In [99]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         50000 non-null  object
 1   AccountNumber      50000 non-null  object
 2   TransactionDate    50000 non-null  datetime64[ns]
 3   TransactionAmount  49401 non-null  float64
 4   TransactionType    50000 non-null  object
 5   AccountBalance     49402 non-null  float64
 6   SPIntercept        50000 non-null  int64
 7   SPTimestamp        50000 non-null  datetime64[ns]
 8   LoginDevice        49700 non-null  object
 9   TransactionDevice  49700 non-null  object
 10  LoginTimestamp     50000 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(1), object(5)
memory usage: 4.2+ MB

In [100]:
df1.describe()

,TransactionDate,TransactionAmount,AccountBalance,SPIntercept,SPTimestamp,LoginTimestamp
count,50000,49401.000000,49402.000000,50000.000000,50000,50000
mean,2022-04-16 16:08:17.088000,18739.995012,499237.698734,0.236960,2022-04-17 04:11:30.049219840,2022-04-17 04:11:12.015379968
min,2020-01-01 00:00:00,10.100000,28.220000,0.000000,2020-01-01 00:50:01,2020-01-01 00:49:58
25%,2021-02-21 00:00:00,3466.710000,247981.172500,0.000000,2021-02-21 22:56:21.249999872,2021-02-21 22:55:42.249999872
50%,2022-04-17 00:00:00,6930.430000,497791.575000,0.000000,2022-04-17 09:31:27.500000,2022-04-17 09:31:14.500000
75%,2023-06-08 00:00:00,17857.120000,750850.082500,0.000000,2023-06-08 06:38:01.249999872,2023-06-08 06:37:58.249999872
max,2024-07-23 00:00:00,99990.590000,999984.310000,1.000000,2024-07-23 20:56:59,2024-07-23 20:56:41
std,NaN,26234.418145,289260.809963,0.425222,NaN,NaN

In [101]:
df1.head()

,CustomerID,AccountNumber,TransactionDate,TransactionAmount,TransactionType,AccountBalance,SPIntercept,SPTimestamp,LoginDevice,TransactionDevice,LoginTimestamp
0,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB30SPXD57546556446883,2020-11-02,8790.43,Online Payment,176954.23,0,2020-11-02 02:59:33,Laptop,Laptop,2020-11-02 02:59:30
1,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB66VKDN90953436305137,2020-12-17,7158.76,ATM Withdrawal,159414.04,1,2020-12-17 02:47:20,Laptop,Desktop,2020-12-17 02:46:31
2,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB31JMIV58178326185913,2022-09-16,61284.18,Money Transfer,998831.12,0,2022-09-16 12:28:49,Desktop,Desktop,2022-09-16 12:28:30
3,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB41JFJR59711046606283,2022-03-15,8244.07,Money Transfer,297781.36,0,2022-03-15 19:09:49,Tablet,Tablet,2022-03-15 19:09:35
4,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB89MWWC02062566820289,2020-09-26,1221.55,Online Payment,791467.34,0,2020-09-26 12:31:52,Mobile,Mobile,2020-09-26 12:31:41

In [102]:
df1.columns

Index(['CustomerID', 'AccountNumber', 'TransactionDate', 'TransactionAmount',
       'TransactionType', 'AccountBalance', 'SPIntercept', 'SPTimestamp',
       'LoginDevice', 'TransactionDevice', 'LoginTimestamp'],
      dtype='object')

In [103]:
missing_data=pd.DataFrame({'total_missing': df1.isnull().sum(),
                           'perc_missing': (df1.isnull().sum()/10000)*100})
missing_data

                   total_missing  perc_missing
CustomerID                     0          0.00
AccountNumber                  0          0.00
TransactionDate                0          0.00
TransactionAmount            599          5.99
TransactionType                0          0.00
AccountBalance               598          5.98
SPIntercept                    0          0.00
SPTimestamp                    0          0.00
LoginDevice                  300          3.00
TransactionDevice            300          3.00
LoginTimestamp                 0          0.00

In [104]:
df1=df1.dropna()

In [105]:
df1.isnull().sum()

CustomerID           0
AccountNumber        0
TransactionDate      0
TransactionAmount    0
TransactionType      0
AccountBalance       0
SPIntercept          0
SPTimestamp          0
LoginDevice          0
TransactionDevice    0
LoginTimestamp       0
dtype: int64

#DATA MERGING

In [106]:
df1

,CustomerID,AccountNumber,TransactionDate,TransactionAmount,TransactionType,AccountBalance,SPIntercept,SPTimestamp,LoginDevice,TransactionDevice,LoginTimestamp
0,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB30SPXD57546556446883,2020-11-02,8790.43,Online Payment,176954.23,0,2020-11-02 02:59:33,Laptop,Laptop,2020-11-02 02:59:30
1,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB66VKDN90953436305137,2020-12-17,7158.76,ATM Withdrawal,159414.04,1,2020-12-17 02:47:20,Laptop,Desktop,2020-12-17 02:46:31
2,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB31JMIV58178326185913,2022-09-16,61284.18,Money Transfer,998831.12,0,2022-09-16 12:28:49,Desktop,Desktop,2022-09-16 12:28:30
3,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB41JFJR59711046606283,2022-03-15,8244.07,Money Transfer,297781.36,0,2022-03-15 19:09:49,Tablet,Tablet,2022-03-15 19:09:35
4,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB89MWWC02062566820289,2020-09-26,1221.55,Online Payment,791467.34,0,2020-09-26 12:31:52,Mobile,Mobile,2020-09-26 12:31:41
...,...,...,...,...,...,...,...,...,...,...,...
49995,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB93WSLH63399166355899,2022-08-19,8169.44,ATM Withdrawal,437970.50,0,2022-08-19 19:07:43,Mobile,Mobile,2022-08-19 19:07:23
49996,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB52YAXA18297356502547,2020-02-20,80673.47,Online Payment,9824.86,0,2020-02-20 02:09:14,Laptop,Laptop,2020-02-20 02:09:00
49997,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB39EWTC90710675739428,2022-09-14,3370.36,ATM Withdrawal,536494.57,0,2022-09-14 23:36:41,Laptop,Laptop,2022-09-14 23:36:34
49998,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB74IOTY57465382870403,2022-06-12,21540.62,Online Payment,810778.90,1,2022-06-12 13:13:17,Tablet,Tablet,2022-06-12 13:12:58
49999,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB59LCPG05581241014409,2020-06-23,9262.94,ATM Withdrawal,813378.31,0,2020-06-23 07:02:55,Mobile,Mobile,2020-06-23 07:02:49

In [107]:
merged_df = pd.merge(df1, df2, on='CustomerID', how='inner')

In [126]:
merged_df

,CustomerID,AccountNumber,TransactionDate,TransactionAmount,TransactionType,AccountBalance,SPIntercept,SPTimestamp,LoginDevice,TransactionDevice,LoginTimestamp,CustomerName,Email,PhoneNumber,Address,DateOfBirth,Gender,Tier,FormattedBalance
0,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB30SPXD57546556446883,2020-11-02,8790.43,Online Payment,176954.23,0,2020-11-02 02:59:33,Laptop,Laptop,2020-11-02 02:59:30,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Standard,"$176,954.23"
1,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB66VKDN90953436305137,2020-12-17,7158.76,ATM Withdrawal,159414.04,1,2020-12-17 02:47:20,Laptop,Desktop,2020-12-17 02:46:31,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Standard,"$159,414.04"
2,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB31JMIV58178326185913,2022-09-16,61284.18,Money Transfer,998831.12,0,2022-09-16 12:28:49,Desktop,Desktop,2022-09-16 12:28:30,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Elite,"$998,831.12"
3,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB41JFJR59711046606283,2022-03-15,8244.07,Money Transfer,297781.36,0,2022-03-15 19:09:49,Tablet,Tablet,2022-03-15 19:09:35,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Premium,"$297,781.36"
4,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB89MWWC02062566820289,2020-09-26,1221.55,Online Payment,791467.34,0,2020-09-26 12:31:52,Mobile,Mobile,2020-09-26 12:31:41,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Elite,"$791,467.34"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48232,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB93WSLH63399166355899,2022-08-19,8169.44,ATM Withdrawal,437970.50,0,2022-08-19 19:07:43,Mobile,Mobile,2022-08-19 19:07:23,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Premium,"$437,970.50"
48233,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB52YAXA18297356502547,2020-02-20,80673.47,Online Payment,9824.86,0,2020-02-20 02:09:14,Laptop,Laptop,2020-02-20 02:09:00,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Standard,"$9,824.86"
48234,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB39EWTC90710675739428,2022-09-14,3370.36,ATM Withdrawal,536494.57,0,2022-09-14 23:36:41,Laptop,Laptop,2022-09-14 23:36:34,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Elite,"$536,494.57"
48235,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB74IOTY57465382870403,2022-06-12,21540.62,Online Payment,810778.90,1,2022-06-12 13:13:17,Tablet,Tablet,2022-06-12 13:12:58,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Elite,"$810,778.90"
48236,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB59LCPG05581241014409,2020-06-23,9262.94,ATM Withdrawal,813378.31,0,2020-06-23 07:02:55,Mobile,Mobile,2020-06-23 07:02:49,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Elite,"$813,378.31"

Defining into tiers

In [113]:
def classify_tier(AccountBalance):
    if AccountBalance <200000:
        return ' Standard'
    elif 200000 <= AccountBalance < 500000:
        return ' Premium'
    else:
        return 'Elite'

# Applying the classification
merged_df['Tier'] = merged_df['AccountBalance'].apply(classify_tier)

In [120]:
# Formatting the Balance column as money
merged_df['FormattedBalance'] = merged_df['AccountBalance'].apply(lambda x: "${:,.2f}".format(x))

In [127]:
merged_df

,CustomerID,AccountNumber,TransactionDate,TransactionAmount,TransactionType,AccountBalance,SPIntercept,SPTimestamp,LoginDevice,TransactionDevice,LoginTimestamp,CustomerName,Email,PhoneNumber,Address,DateOfBirth,Gender,Tier,FormattedBalance
0,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB30SPXD57546556446883,2020-11-02,8790.43,Online Payment,176954.23,0,2020-11-02 02:59:33,Laptop,Laptop,2020-11-02 02:59:30,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Standard,"$176,954.23"
1,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB66VKDN90953436305137,2020-12-17,7158.76,ATM Withdrawal,159414.04,1,2020-12-17 02:47:20,Laptop,Desktop,2020-12-17 02:46:31,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Standard,"$159,414.04"
2,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB31JMIV58178326185913,2022-09-16,61284.18,Money Transfer,998831.12,0,2022-09-16 12:28:49,Desktop,Desktop,2022-09-16 12:28:30,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Elite,"$998,831.12"
3,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB41JFJR59711046606283,2022-03-15,8244.07,Money Transfer,297781.36,0,2022-03-15 19:09:49,Tablet,Tablet,2022-03-15 19:09:35,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Premium,"$297,781.36"
4,e0497be9-6494-4efb-b575-fe9f55fccfe4,GB89MWWC02062566820289,2020-09-26,1221.55,Online Payment,791467.34,0,2020-09-26 12:31:52,Mobile,Mobile,2020-09-26 12:31:41,Sara Chen,aguirrealison@example.com,422-973-7577x76091,"8664 Butler Ramp\nEast Scott, OK 87220",1972-09-15,Male,Elite,"$791,467.34"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48232,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB93WSLH63399166355899,2022-08-19,8169.44,ATM Withdrawal,437970.50,0,2022-08-19 19:07:43,Mobile,Mobile,2022-08-19 19:07:23,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Premium,"$437,970.50"
48233,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB52YAXA18297356502547,2020-02-20,80673.47,Online Payment,9824.86,0,2020-02-20 02:09:14,Laptop,Laptop,2020-02-20 02:09:00,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Standard,"$9,824.86"
48234,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB39EWTC90710675739428,2022-09-14,3370.36,ATM Withdrawal,536494.57,0,2022-09-14 23:36:41,Laptop,Laptop,2022-09-14 23:36:34,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Elite,"$536,494.57"
48235,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB74IOTY57465382870403,2022-06-12,21540.62,Online Payment,810778.90,1,2022-06-12 13:13:17,Tablet,Tablet,2022-06-12 13:12:58,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Elite,"$810,778.90"
48236,5b35e7e2-25d5-4c37-908c-73b81cac087e,GB59LCPG05581241014409,2020-06-23,9262.94,ATM Withdrawal,813378.31,0,2020-06-23 07:02:55,Mobile,Mobile,2020-06-23 07:02:49,Tamara Johnson,stephanie38@example.com,679.960.6947,"844 Walker Path\nNorth Robert, GA 40730",1913-02-09,Female,Elite,"$813,378.31"

In [130]:
import nbformat
from nbformat.validator import validate, ValidationError

notebook_path = 'C:\Users\mmost\OneDrive\Desktop\intern\proj.ipynb'

try:
    with open(notebook_path, 'r', encoding='utf-8') as f:
        notebook = nbformat.read(f, as_version=4)
    validate(notebook)
    print("Notebook is valid JSON.")
except ValidationError as e:
    print(f"Notebook is invalid: {e}")
    # Attempt to repair
    repaired_notebook = nbformat.convert(notebook, to_version=4)
    with open(notebook_path, 'w', encoding='utf-8') as f:
        nbformat.write(repaired_notebook, f)
    print("Notebook has been repaired.")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (2396746319.py, line 4)